USE BasketballTournamentsApp
GO

DROP PROCEDURE IF EXISTS GET_TEAM_MEMBER_REGISTRATIONS
DROP PROCEDURE IF EXISTS ADD_TEAM_MEMBER_REGISTRATION
DROP PROCEDURE IF EXISTS DELETE_TEAM_MEMBER_REGISTRATION
DROP PROCEDURE IF EXISTS UPDATE_TEAM_MEMBER_REGISTRATION
GO

CREATE PROCEDURE GET_TEAM_MEMBER_REGISTRATIONS
AS
BEGIN
	SELECT  
	UserId,
	TeamId,
	JoinedAt
    FROM TeamMemberRegistration
END
GO
EXEC GET_TEAM_MEMBER_REGISTRATIONS;
GO

CREATE PROCEDURE ADD_TEAM_MEMBER_REGISTRATION
	@UserId INT,
	@TeamId INT,
	@JoinedAt DATETIME=NULL
AS
BEGIN

IF @JoinedAt IS NULL
        SET @JoinedAt = GETDATE();

INSERT INTO TeamMemberRegistration(
    UserId,
	TeamId,
	JoinedAt
)
VALUES (
    @UserId,
	@TeamId,
	@JoinedAt
);

END
GO

CREATE PROCEDURE DELETE_TEAM_MEMBER_REGISTRATION(@UserId INT, @TeamId INT)
AS
BEGIN
    DELETE FROM TeamMemberRegistration WHERE UserId=@UserId AND TeamId=@TeamId
END

GO

CREATE PROCEDURE UPDATE_TEAM_MEMBER_REGISTRATION
    @UserId INT,
	@TeamId INT,
	@JoinedAt DATETIME=NULL
AS
BEGIN
    UPDATE TeamMemberRegistration
    SET 
	JoinedAt=@JoinedAt
    WHERE UserId=@UserId AND TeamId=@TeamId
END
GO

